services:
  app:
    ports:
      - "5000${SERVER_ADDRESS}"
    expose:
      - 5000
    restart: always
    depends_on:
    - db
    networks:
      notes-api:
    build:
      dockerfile: Dockerfile
      context: .
  db:
    networks:
      notes-api:
    image: mysql:8
    restart: always
    command: --init-file /var/lib/init.sql
    env_file:
      .env
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/var/lib/init.sql

networks:
  notes-api:
# Names our volume
volumes:
  my-db: